// src/components/Counter.jsx
import { counter } from "../stores/counterStore";
import { useStore } from "@nanostores/react";

export default function Counter() {
  const counterValue = useStore(counter);
  return (
    <div style={{ display: "flex", gap: "20px" }}>
      React Counter Component
      <button onClick={() => counter.set(counterValue + 1)}>
        Clicked {counterValue} times
      </button>
    </div>
  );
}

// src/components/Counter.vue
<template>
  <div style="display: flex; gap: 20px">
    Vue Counter Component
    <button @click="counter.set(counterValue + 1)">
      Clicked {{ counterValue }} times
    </button>
  </div>
</template>

<script setup>
import { useStore } from "@nanostores/vue";
import { counter } from "../stores/counterStore";

const counterValue = useStore(counter);
</script>
